name: Reusable Dependency Scan

on:
  workflow_call:

jobs:
  dependency-scan:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@v3
        with:
          project: "cloud-security-projects"
          path: "."
          format: "HTML"
          out: "dependency-check-report"
          args: >
            --failOnCVSS 9
